var ACTIONS;

(function (ACTIONS) {
  ACTIONS[ACTIONS["REGISTER_HOST"] = 0] = "REGISTER_HOST";
  ACTIONS[ACTIONS["ADD_UPDATE_PORTAL"] = 1] = "ADD_UPDATE_PORTAL";
  ACTIONS[ACTIONS["REMOVE_PORTAL"] = 2] = "REMOVE_PORTAL";
})(ACTIONS || (ACTIONS = {}));

const INITIAL_STATE = {};
export { ACTIONS, INITIAL_STATE };
//# sourceMappingURL=constants.js.map